id: I94487933
legacy_id: P006873
ocr_import_info:
  bdrc_scan_id: W27913
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T06:21:30'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T08:08:00.444302+00:00'
last_modified: 2022-09-02 16:08:27.109514
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27913
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW27913
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རིས་མེད་ཆོས་འབྱུང་།
  author: རག་མགོ་མཆོག་སྤྲུལ་ཐུབ་བསྟན་བཤད་སྒྲུབ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.7187875747255275
  ocr_word_median_confidence_index: 0.8199999928474426
quality: null
bases:
  I4514:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4514
      total_pages: 161
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I4514.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7187875747255275
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
